services:
  - type: web
    name: hh-goa-frame-id
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn frameid.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PUBLIC_BASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
