import { useState } from 'react';
import { ArrowRight, Check, Sparkles } from 'lucide-react';
import Button from '../components/Button';
import CardPreview from '../components/CardPreview';
import FormInput from '../components/FormInput';
import LoadingSpinner from '../components/LoadingSpinner';
import PhotoUpload from '../components/PhotoUpload';
import useCardGenerator from '../hooks/useCardGenerator';
import { downloadImage } from '../utils/downloadImage';
import { shareToTwitter } from '../utils/twitterShare';

export default function Home() {
  const [file, setFile] = useState(null); const [name, setName] = useState(''); const [role, setRole] = useState(''); const [errors, setErrors] = useState({}); const { result, loading, error: apiError, generate } = useCardGenerator();
  const submit = async (event) => { event.preventDefault(); const next = {}; if (!file) next.file = 'Please add a photo to continue.'; if (!name.trim()) next.name = 'Your name is required.'; if (name.trim().length > 40) next.name = 'Your name must be 40 characters or fewer.'; if (!role.trim()) next.role = 'Your role or stack is required.'; if (role.trim().length > 60) next.role = 'Your role or stack must be 60 characters or fewer.'; setErrors(next); if (Object.keys(next).length) return; await generate(file, name.trim(), role.trim()); };
  const handleDownload = () => result && downloadImage(result.imageUrl).catch(() => setErrors({ form: 'We could not download your card. Please try again.' }));
  return <main className="min-h-screen overflow-hidden bg-[#101215] text-white">
    <div className="pointer-events-none absolute -left-28 -top-28 h-72 w-72 rounded-full bg-[#d8ff44]/10 blur-3xl" /><header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#d8ff44] text-sm font-black text-[#101215]">HH</span><span className="text-sm font-bold tracking-tight">Frame in Goa <span className="text-white/40">/ 2026</span></span></div><span className="text-xs font-bold uppercase tracking-[.18em] text-white/40">Builder portal</span></header>
    <div className="mx-auto grid max-w-6xl gap-10 px-5 pb-16 pt-10 sm:px-8 lg:grid-cols-[1fr_460px] lg:items-start lg:gap-20 lg:pt-20">
      <div className="max-w-xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#d8ff44]/20 bg-[#d8ff44]/10 px-3 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-[#d8ff44]"><Sparkles size={13} />Hackathon shortlisted</div><h1 className="text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-7xl">Make your mark<br /><span className="text-[#d8ff44]">in Goa.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-white/55">Create your official Builder ID for HH Goa 2026. Upload a photo, tell us what you build, and share your frame with the world.</p><div className="mt-9 hidden gap-6 text-xs text-white/45 sm:flex"><span><Check size={14} className="mr-1 inline text-[#d8ff44]" />Built for builders</span><span><Check size={14} className="mr-1 inline text-[#d8ff44]" />Ready to share</span></div></div>
      <div className="rounded-3xl border border-white/10 bg-[#17191d] p-5 shadow-2xl sm:p-7"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/35">01 — Create your ID</p><h2 className="mt-2 text-2xl font-bold">Show us what you’re building.</h2></div><form onSubmit={submit} className="space-y-5" noValidate><PhotoUpload file={file} onChange={(next) => { setFile(next); setErrors((e) => ({ ...e, file: '' })); }} error={errors.file} /><FormInput id="name" label="Your name" placeholder="e.g. Aisha Khan" value={name} maxLength={40} onChange={(e) => { setName(e.target.value); setErrors((e) => ({ ...e, name: '' })); }} error={errors.name} /><FormInput id="role" label="Role / tech stack" placeholder="e.g. Product designer · React" value={role} maxLength={60} onChange={(e) => { setRole(e.target.value); setErrors((e) => ({ ...e, role: '' })); }} error={errors.role} />{(apiError || errors.form) && <p role="alert" className="rounded-xl border border-red-300/20 bg-red-400/10 p-3 text-xs text-red-200">{apiError || errors.form}</p>}<Button type="submit" disabled={loading} className="w-full">{loading ? <><LoadingSpinner />Generating your ID…</> : <>Generate my Builder ID <ArrowRight size={17} /></>}</Button><p className="text-center text-[11px] text-white/25">By continuing, you agree to share your builder profile publicly.</p></form></div>
      {result && <div className="lg:col-span-2 lg:mx-auto lg:w-[460px]"><CardPreview imageUrl={result.imageUrl} onDownload={handleDownload} onShare={() => shareToTwitter(result.shareId, name)} /></div>}
    </div><footer className="mx-auto flex max-w-6xl justify-between border-t border-white/10 px-5 py-6 text-[11px] text-white/25 sm:px-8"><span>HH Goa 2026</span><span>Built with the Frame community</span></footer>
  </main>;
}
